config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end

  devise_for :users

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  root 'home#index'

  resources :events do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
    resources :attendances, only: [:create]
  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :attendee, class_name: "User", foreign_key: "user_id"
  belongs_to :attended_event, class_name: "Event", foreign_key: "event_id"
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name

  has_many :events
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :author, class_name: "User"

  validates :body, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessor :tag_list

  searchkick
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :organizer, class_name: "User", foreign_key: "user_id"
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances
  has_many :likes, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, length: {minimum: 5}
  validates :venue, presence: true
  validates :location, presence: true


  mount_uploader :image, ImageUploader

  def tag_list
    tags.join(", ")
  end

  def tag_list=(names)
    tag_names = names.split(",").collect {|str| str.strip.downcase}.uniq
    new_or_existing_tags = tag_names.collect {|tag_name| Tag.find_or_create_by(name: tag_name)}
    self.tags = new_or_existing_tags
  end



  def seats_left
    seats - attendees.count
  end

  def seats_left?
    seats == attendees.count
  end

  def likes_total
    self.likes.where(like: "like").count
  end

  def dislikes_total
    self.likes.where(like: "dislike").count
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :event
  belongs_to :user


  validates_uniqueness_of :user_id, scope: :event
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name

  has_many :taggings, dependent: :destroy
  has_many :events, through: :taggings


  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username

  has_many :organized_events, class_name: "Event", dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :username, presence: true, length: {minimum: 6}

  def to_s
    "#{username}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event
  before_action :authenticate_user!
  # skip_after_action :verify_authorized

  def create
    @comment = @event.comments.build(comment_params)
    @comment.author = current_user
    authorize @comment, :create?

    if @comment.save
      flash[:notice] = "Comment has been added to event"
      redirect_to event_path(@comment.event)
    else
      flash.now[:alert] = "Comment has not been added to event"
      render "events/show"
    end
  end






  private
    def set_event
      @event = Event.friendly.find(params[:event_id])
    end


    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # before_action :authorize_owner!, only: [:edit, :update, :destroy]

  def index
    if params[:query].present?
      @events = Event.search(params[:query])
    else
      @events = Event.order(created_at: :desc).paginate(page: params[:page], per_page: 4)
    end
    @categories = Category.order(:name)
    authorize @events, :index?
  end

  def show
    authorize @event, :show?
    @comment = Comment.new
    @comment.event_id = @event.id
  end

  def new
    @event = Event.new

    authorize @event, :new?
  end

  def create
    @event = Event.new(event_params)

    authorize @event, :create?
    @event.organizer = current_user

    if @event.save
      flash[:notice] = "Event created!"
      redirect_to @event
    else
      flash.now[:alert] = "Event not created"
      render "new"
    end
  end


  def edit
    authorize @event, :edit?
  end

  def update
    authorize @event, :update?
    if @event.update(event_params)
      flash[:notice] = "Event updated!"
      redirect_to @event
    else
      flash.now[:alert] = "Event not updated!"
      render "edit"
    end
  end

  def destroy
    authorize @event, :destroy?
    @event.destroy
    flash[:alert] = "Event deleted successfully"
    redirect_to events_url
  end



  private

    def set_event
      @event = Event.friendly.find(params[:id])

      # authorize @event

    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The page you just requested does not exist"
      redirect_to events_path
    end

    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date, :venue, :location, :image, :category_id, :seats, :tag_list)
    end

    # def authorize_owner!
    #   authenticate_user!

    #   unless @event.organizer == current_user
    #     flash[:alert] = "You do not have enough permission to '#{action_name}' the '#{@event.title.upcase}' event"
    #     redirect_to events_path
    #   end
    # end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_authorized

  def index

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_event
  before_action :authenticate_user!
  skip_after_action :verify_authorized

  def create
    @like = @event.likes.where(like: params[:like], user_id: current_user).create

    if @like.valid?
      flash[:notice] = "You #{params[:like]} this event"
    else
      flash[:alert] = "You've already made your choice."
    end
    redirect_to event_path(@event)
  end



  private

    def set_event
      @event = Event.friendly.find(params[:event_id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_after_action :verify_authorized


  def show
    @tag = Tag.friendly.find(params[:id])
    @categories = Category.order(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  skip_after_action :verify_authorized


  def show
  end




  private

    def set_user
      @user = User.friendly.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    default_title = "Eventsboard - Create Events to Socialize"
    if page_title.empty?
      default_title
    else
      "#{page_title} | #{default_title}"
    end
  end

  def time_format(event_date)
    event_date.strftime("%A, %d %b %Y %l:%M %p")
  end

  def event_status(event)
    if event.end_date <= Date.today
      content_tag(:span, "", class: "past")
    else
      content_tag(:span, "", class: "upcoming")
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end

  def avatar_url(user)
    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

<%= simple_form_for(event) do |f| %>

  <%= f.input :title %>

  <%= f.input :description %>

  <%= f.input :start_date, as: :datetime, start_year: Date.today.year, ampm: true, order: [:day, :month, :year] %>

  <%= f.input :end_date, as: :datetime, start_year: Date.today.year, ampm: true, order: [:day, :month, :year] %>

  <%= f.input :venue %>

  <%= f.input :location %>

  <%= f.input :category_id, collection: Category.all, label: "Select Category", prompt: true %>

  <%= f.input :seats, label: "Capacity", hint: "The number of attendees to the event" %>

  <%= f.input :tag_list, label: "Tags", hint: "Please enter comma separated words only." %>

  <%= f.input :image, as: :file, label: "Upload Event Image" %>

  <%= f.button :submit, class: "btn btn-primary" %>

<% end %>

  <p><%= link_to "Back", events_path %></p>
  </div>
</div>

app/views/events/edit.html.erb
<header>
  <h1>Edit Event</h1>
</header>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<header>
  <h1>All Events</h1>

  <ul class="actions">
    <li><%= link_to "New Event", new_event_path, class: "new" if policy(Event).new? %></li>
  </ul>
</header>

<div class="row">
  <div class="col-sm-3 pull-right">
    <div class="sidebar">
      <h3 class="discover">Discover</h3>
      <ul class="nav nav-pills nav-stacked">
        <li class="<%= "active" if current_page?("/events")%>"><%= link_to "ALL EVENTS", events_path %></li>
        <% @categories.each do |category| %>
          <li class="<%= "active" if current_page?("/categories/#{category.id}")%> text-uppercase">
            <%= link_to category.name, category_path(category) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="search">
    <div class="col-sm-9">
      <h4>Discover and register to attend your favourite events right here</h4>
      <%= form_tag events_path, class: "form-horizontal", method: :get do  %>
        <div class="form-group form-group-lg">
          <div class="col-sm-10">
            <%= text_field_tag :query, params[:query], placeholder: "Search events here..", autofocus: true, class: "form-control" %>
          </div>
          <div class="col-sm-2">
            <%= submit_tag "Find", class: "btn btn-default btn-lg" %>
            <% if params[:query].present? %>
              <%= link_to "Clear", events_path %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<% @events.each do |event| %>
 <div class="col-sm-9 pull-left">
   <%= link_to event_path(event) do %>
    <div class="events">
      <div class="row">
        <div class="col-sm-3">
          <%= image_tag event.image.url, class: "event-image" %>
        </div>
        <div class="col-sm-9">
          <h3 class="event-title"><%= event.title %></h3>
          <p>
            <span class="event-venue"><%= event.venue %> - <strong><%= event.location %></strong></span>
          </p>
          <p class="lead-time">
            <span class="event-start"><%= time_format(event.start_date) %></span> <span class="pull-right">Organized by: <%= event.organizer %></span>
          </p>
          <p class="index-icons">
            <span><%= fa_icon "comments" %> <%= event.comments.count %></span>
            <span><%= fa_icon "thumbs-o-up" %> <%= event.likes_total %></span>
            <span><%= fa_icon "thumbs-o-down" %> <%= event.dislikes_total %></span>
          </p>
        </div>
      </div>
    </div>
   <% end %>
 </div>
<% end %>
</div>

<div class="text-center">
   <%= will_paginate @events %>
</div>

app/views/events/new.html.erb
<header>
  <h1>New Event</h1>
</header>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>

<header>
  <h1 id="show-title"><%= @event.title %></h1>

  <ul class="actions">
    <li><%= link_to "Edit Event", edit_event_path(@event), class: "edit" if policy(@event).edit? %></li>
    <li><%= link_to "Delete Event", event_path(@event), method: :delete, data: {confirm: "Are you sure?"}, class: "delete" if policy(@event).destroy? %></li>
    <% if @event.seats_left? %>
      <li class="label label-danger text-uppercase">No Seats Available</li>
    <% else %>
      <li><%= link_to "Register", event_attendances_path(@event), method: :post, class: "new" %></li>
    <% end %>
  </ul>
</header>

<div class="row">
  <div class="col-sm-9">
    <%= image_tag @event.image.url, class: "event-image" %>
    <div class="event-meta">
      <h4><span class="event-start"><strong>Starts:</strong> <%= time_format(@event.start_date) %></span></h4>
      <p>
        <span class="event-end"><strong>Ends:</strong> <%= time_format(@event.end_date) %></span>
      </p>
    </div>

    <div class="event-details">
      <h3>Event Details</h3>
      <p><%= @event.description %></p>
    </div>

    <header>
      <h3>Comments</h3>
    </header>

    <div id="comments">
      <% if @event.comments.any? %>
        <%= render @event.comments %>
      <% else %>
        <p>There are no comments for this event</p>
      <% end %>
    </div>
      <%= render "comments/form", event: @event, comment: @comment if policy(@comment).create? %>
  </div>

  <div class="col-sm-3">
    <div class="sidebar">
      <h4 class="organizer"><%= link_to @event.organizer, user_path(@event.organizer) %></h4>
      <p>
        <span class="event-venue"><%= @event.venue %>, <strong><%= @event.location %></strong></span>
      </p>
    </div>
    <hr>
    <div class="sidebar">
      <h4 class="tags">Tags</h4>
      <% if @event.tags.any? %>
        <%= render @event.tags %>
      <% end %>
    </div>
    <hr>
    <div class="sidebar">
      <h4 class="attendees">Attendees <span class="pull-right"><%= @event.attendees.count %></span></h4>
      <span class="label label-default pull-right <%= "hidden" if @event.seats_left? %>"><%= pluralize(@event.seats_left, "Seat" )%> Available</span>
    </div>
    <hr>
    <div class="sidebar">
      <h4 class="likes">Likes</h4>
      <%= link_to event_likes_path(@event, like: "like"), method: :post do %>
        <span id="like"><%= @event.likes_total %></span>
      <% end %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to event_likes_path(@event, like: "dislike"), method: :post do %>
        <span id="dislike"><%= @event.dislikes_total %></span>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/_tag.html.erb
<%= link_to tag_path(tag) do %>
  <span class="tag"><%= fa_icon "hashtag" %><%= tag %></span>
<% end %>

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %>

<header>
 <h1>Events tagged: <strong><em><%= @tag.name %></em></strong></h1>
</header>

<div class="row">
  <div class="col-sm-3 pull-right">
    <div class="sidebar">
      <h3 class="discover">Discover</h3>
      <ul class="nav nav-pills nav-stacked">
        <li class="<%= "active" if current_page?("/events")%>"><%= link_to "ALL EVENTS", events_path %></li>
        <% @categories.each do |category| %>
          <li class="<%= "active" if current_page?("/categories/#{category.id}")%> text-uppercase">
            <%= link_to category.name, category_path(category) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="search">
    <div class="col-sm-9">
      <h4>Discover and register to attend your favourite events right here</h4>
      <%= form_tag events_path, class: "form-horizontal", method: :get do  %>
        <div class="form-group form-group-lg">
          <div class="col-sm-10">
            <%= text_field_tag :query, params[:query], placeholder: "Search events here..", autofocus: true, class: "form-control" %>
          </div>
          <div class="col-sm-2">
            <%= submit_tag "Find", class: "btn btn-default btn-lg" %>
            <% if params[:query].present? %>
              <%= link_to "Clear", events_path %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<% @tag.events.each do |event| %>
 <div class="col-sm-9 pull-left">
   <%= link_to event_path(event) do %>
    <div class="events">
      <div class="row">
        <div class="col-sm-3">
          <%= image_tag event.image.url, class: "event-image" %>
        </div>
        <div class="col-sm-9">
          <h3 class="event-title"><%= event.title %></h3>
          <p>
            <span class="event-venue"><%= event.venue %> - <strong><%= event.location %></strong></span>
          </p>
          <p class="lead-time">
            <span class="event-start"><%= time_format(event.start_date) %></span> <span class="pull-right">Organized by: <%= event.organizer %></span>
          </p>
        </div>
      </div>
    </div>
   <% end %>
 </div>
<% end %>
</div>
</div>