config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end

  devise_for :users

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  root 'home#index'

  resources :events do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
    resources :attendances, only: [:create]
  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :attendee, class_name: "User", foreign_key: "user_id"
  belongs_to :attended_event, class_name: "Event", foreign_key: "event_id"
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name

  has_many :events
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :author, class_name: "User"

  validates :body, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessor :tag_list

  searchkick
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :organizer, class_name: "User", foreign_key: "user_id"
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances
  has_many :likes, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, length: {minimum: 5}
  validates :venue, presence: true
  validates :location, presence: true


  mount_uploader :image, ImageUploader

  def tag_list
    tags.join(", ")
  end

  def tag_list=(names)
    tag_names = names.split(",").collect {|str| str.strip.downcase}.uniq
    new_or_existing_tags = tag_names.collect {|tag_name| Tag.find_or_create_by(name: tag_name)}
    self.tags = new_or_existing_tags
  end



  def seats_left
    seats - attendees.count
  end

  def seats_left?
    seats == attendees.count
  end

  def likes_total
    self.likes.where(like: "like").count
  end

  def dislikes_total
    self.likes.where(like: "dislike").count
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :event
  belongs_to :user


  validates_uniqueness_of :user_id, scope: :event
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name

  has_many :taggings, dependent: :destroy
  has_many :events, through: :taggings


  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username

  has_many :organized_events, class_name: "Event", dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :username, presence: true, length: {minimum: 6}

  def to_s
    "#{username}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  skip_after_action :verify_authorized

  def index
    @users = User.all
    @events = Event.all
    @categories = Category.all
    @comments = Comment.all
    @attendances = Attendance.all
    @likes = Like.all
    @tags = Tag.all
  end



  private


  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Pundit


  after_action :verify_authorized, unless: :devise_controller?
  before_filter :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized



  private


    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user|
        user.permit(:email, :password, :password_confirmation, :first_name, :last_name, :username, :organization_name)
      end

      devise_parameter_sanitizer.permit(:account_update) do |user|
        user.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :username, :organization_name)
      end
    end

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform that action"
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_authorized

  def index

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_event
  before_action :authenticate_user!
  skip_after_action :verify_authorized

  def create
    @like = @event.likes.where(like: params[:like], user_id: current_user).create

    if @like.valid?
      flash[:notice] = "You #{params[:like]} this event"
    else
      flash[:alert] = "You've already made your choice."
    end
    redirect_to event_path(@event)
  end



  private

    def set_event
      @event = Event.friendly.find(params[:event_id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_after_action :verify_authorized


  def show
    @tag = Tag.friendly.find(params[:id])
    @categories = Category.order(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  skip_after_action :verify_authorized


  def show
  end




  private

    def set_user
      @user = User.friendly.find(params[:id])
    end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    default_title = "Eventsboard - Create Events to Socialize"
    if page_title.empty?
      default_title
    else
      "#{page_title} | #{default_title}"
    end
  end

  def time_format(event_date)
    event_date.strftime("%A, %d %b %Y %l:%M %p")
  end

  def event_status(event)
    if event.end_date <= Date.today
      content_tag(:span, "", class: "past")
    else
      content_tag(:span, "", class: "upcoming")
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end

  def avatar_url(user)
    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/application/index.html.erb
<div class="row">
  <div class="col-sm-3 admin">
    <div class="admin-sidebar">
      <div class="user-panel">
        <div class="pull-left image">
          <%= image_tag avatar_url(current_user), width: 20, class: "img-circle" %>
        </div>
        <div class="pull-left info">
        <p><%= current_user.full_name %></p>
        </div>
      </div>
    </div>
    <ul class="admin-menu">
      <li class="text-uppercase text-center header">Main Navigation</li>
      <li>
        <%= link_to admin_users_path do %>
          <%= fa_icon "users" %>
          <span>Users</span>
          <span class="label label-primary pull-right"><%= @users.count %></span>
        <% end %>
      </li>

      <li>
        <%= link_to admin_categories_path do %>
          <%= fa_icon "th" %>
          <span>Categories</span>
          <span class="label label-info pull-right"><%= @categories.count %></span>
        <% end %>
      </li>

      <li>
        <%= link_to admin_attendances_path do %>
          <%= fa_icon "user" %>
          <span>Attendees</span>
          <span class="label label-danger pull-right"><%= @attendances.count %></span>
        <% end %>
      </li>

      <li>
        <%= link_to events_path do %>
          <%= fa_icon "calendar" %>
          <span>Events</span>
          <span class="label label-warning pull-right"><%= @events.count %></span>
        <% end %>
      </li>

      <li>
        <%= link_to "#" do %>
          <%= fa_icon "tag" %>
          <span>Tags</span>
          <span class="label label-default pull-right"><%= @tags.count %></span>
        <% end %>
      </li>

      <li>
        <%= link_to admin_comments_path do %>
          <%= fa_icon "comments" %>
          <span>Comments</span>
          <span class="label label-primary pull-right"><%= @comments.count %></span>
        <% end %>
      </li>

      <li>
        <%= link_to "#" do %>
          <%= fa_icon "heart" %>
          <span>Likes</span>
          <span class="label label-danger pull-right"><%= @likes.count %></span>
        <% end %>
      </li>
    </ul>
  </div>

    <div class="col-sm-9">
      <header>
        <h1>Dashboard <small>Control Panel</small></h1>
      </header>

      <h4>Welcome to Admin Dashboard of Eventsboard</h4>
    </div>
</div>