config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end

  devise_for :users

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  root 'home#index'

  resources :events do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
    resources :attendances, only: [:create]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name

  has_many :events
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]


  def index
    @categories = Category.order(:name)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category has been created."
      redirect_to admin_categories_path
    else
      flash.now[:alert] = "Category has not been created."
      render "new"
    end
  end

  def edit

  end

  def update

    if @category.update(category_params)
      flash[:notice] = "Category has been updated."
      redirect_to admin_categories_path
    else
      flash.now[:alert] = "Category has not been updated."
      render "edit"
    end

  end

  def destroy
    @category.destroy

    flash[:alert] = "Category has been deleted."
    redirect_to admin_categories_path

  end


  private

    def category_params
      params.require(:category).permit(:name, :summary)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  skip_after_action :verify_authorized

  def show
    @categories = Category.order(:name)
    @category_events = @category.events.order(created_at: :desc).paginate(page: params[:page], per_page: 1)
  end


  private


    def set_category
      @category = Category.friendly.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The category you were looking for could be found."
      redirect_to(request.referrer || events_url)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= simple_form_for([:admin, category]) do |f| %>
      <%= f.input :name %>

      <%= f.input :summary %>

      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<header>
  <h1>Edit Category <small>(<%= @category.name %>)</small></h1>

  <%= render "form", category: @category %>
</header>

app/views/admin/categories/index.html.erb
<header>
  <h1>Categories</h1>

  <% admins_only do %>
    <ul class="actions">
      <li><%= link_to "New Category", new_admin_category_path, class: "new" %></li>
    </ul>
  <% end %>
</header>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created</th>
      <th>Events</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category|  %>
      <tr>
        <td><%= category.name %></td>
        <td><%= time_format(category.created_at) %></td>
        <td><%= category.events.count %></td>
        <td>
          <%= link_to "View", category_path(category) %> | <%= link_to "Edit", edit_admin_category_path(category) %> | <%= link_to "Delete", admin_category_path(category), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/admin/categories/new.html.erb
<header>
  <h1>New Category</h1>
</header>

<%= render "form", category: @category %>