config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end

  devise_for :users

  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :tags, only: [:show]
  root 'home#index'

  resources :events do
    resources :likes, only: [:create]
    resources :comments, only: [:create]
    resources :attendances, only: [:create]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name

  has_many :events
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]


  def index
    @categories = Category.order(:name)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category has been created."
      redirect_to admin_categories_path
    else
      flash.now[:alert] = "Category has not been created."
      render "new"
    end
  end

  def edit

  end

  def update

    if @category.update(category_params)
      flash[:notice] = "Category has been updated."
      redirect_to admin_categories_path
    else
      flash.now[:alert] = "Category has not been updated."
      render "edit"
    end

  end

  def destroy
    @category.destroy

    flash[:alert] = "Category has been deleted."
    redirect_to admin_categories_path

  end


  private

    def category_params
      params.require(:category).permit(:name, :summary)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  skip_after_action :verify_authorized

  def show
    @categories = Category.order(:name)
    @category_events = @category.events.order(created_at: :desc).paginate(page: params[:page], per_page: 1)
  end


  private


    def set_category
      @category = Category.friendly.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The category you were looking for could be found."
      redirect_to(request.referrer || events_url)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>

<header>
  <h1 class="text-uppercase"><%= @category.name %> <small>Events</small></h1>


  <ul class="actions">
    <% admins_only do  %>
      <li><%= link_to "Edit Category", edit_admin_category_path(@category), class: "edit" %></li>

      <li><%= link_to "Delete Category", admin_category_path(@category), method: :delete, data: {confirm: "Are you sure you want to delete this category?"}, class: "delete" %></li>
    <% end %>
  </ul>
</header>

<div class="row">
  <div class="col-sm-3 pull-right">
    <div class="sidebar">
      <h3 class="discover">Discover</h3>
      <ul class="nav nav-pills nav-stacked">
        <li class="<%= "active" if current_page?("/events")%>"><%= link_to "ALL EVENTS", events_path %></li>
        <% @categories.each do |category| %>
          <li class="<%= "active" if current_page?("/categories/#{category.id}")%> text-uppercase">
            <%= link_to category.name, category_path(category) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="search">
    <div class="col-sm-9">
      <h4>Discover and register to attend your favourite events right here</h4>
      <%= form_tag events_path, class: "form-horizontal", method: :get do  %>
        <div class="form-group form-group-lg">
          <div class="col-sm-10">
            <%= text_field_tag :query, params[:query], placeholder: "Search events here..", autofocus: true, class: "form-control" %>
          </div>
          <div class="col-sm-2">
            <%= submit_tag "Find", class: "btn btn-default btn-lg" %>
            <% if params[:query].present? %>
              <%= link_to "Clear", events_path %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<% @category_events.each do |event| %>
 <div class="col-sm-9 pull-left">
   <%= link_to event_path(event) do %>
    <div class="events">
      <div class="row">
        <div class="col-sm-3">
          <%= image_tag event.image.url, class: "event-image" %>
        </div>
        <div class="col-sm-9">
          <h3 class="event-title"><%= event.title %></h3>
          <p>
            <span class="event-venue"><%= event.venue %> - <strong><%= event.location %></strong></span>
          </p>
          <p class="lead-time">
            <span class="event-start"><%= time_format(event.start_date) %></span> <span class="pull-right">Organized by: <%= event.organizer %></span>
          </p>
        </div>
      </div>
    </div>
   <% end %>
 </div>
<% end %>
</div>
</div>

<div class="text-center">
  <%= will_paginate @category_events %>
</div>